#sh -c 'echo "input website:"; read website; echo "searching..."; sleep 1; curl http://$website;'


FROM ubuntu:20.04

WORKDIR /usr/src/app

#CMD apt-get update; apt-get install -y curl; echo "input website"; read website; echo "Searching..."; sleep 1; curl http://$website;

COPY curler.sh .

RUN apt-get update; apt-get install -y curl;chmod +x curler.sh

CMD ./curler.sh
