FROM ubuntu

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y nodejs

RUN npm install && npm install -g serve && npm run build

#added for exercise 1.14
ENV REACT_APP_BACKEND_URL=http://localhost:8080
CMD ["serve", "-s", "-l", "5000", "build"]

EXPOSE 5000
