
FROM ubuntu:20.04

WORKDIR /mydir

#RUN apt-get update && apt-get install -y curl
RUN apt-get update && apt-get install -y curl software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
RUN chmod a+rx /usr/local/bin/yt-dlp

ENV LC_ALL=C.UTF-8

#ENTRYPOINT ["/usr/local/bin/yt-dlp"]
#ENTRYPOINT /usr/local/bin/yt-dlp
#CMD ["-o","ytexample.txt","BaW_jenozKc"]
#CMD -o - BaW_jenozKc > ytexample.txt
CMD yt-dlp -o - BaW_jenozKc > ytexample.txt
